services:
  - type: web
    name: halterai-backend
    env: python
    plan: starter
    buildCommand: ""
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: "${FIREBASE_PROJECT_ID}"
      - key: FIREBASE_API_KEY
        value: "${FIREBASE_API_KEY}"
      - key: GEMINI_API_KEY
        value: "${GEMINI_API_KEY}"
  - type: static_site
    name: halterai-frontend
    env: static
    plan: starter
    publishPath: public 
